### ISSUE TITLE
pysmf is not listed on PyPI

### ISSUE THREAD

**Issue by SpotlightKid** [dsacre/pysmf#1]
For this reason it is not easily installable via pip.

pysmf should have a PyPI entry and the latest source distribution package should be hosted there.

At the moment one needs to know/use the URL of the source distribution to install with pip:

pip install http://das.nasophon.de/download/pysmf-0.1.0.tar.gz

See also the related [issue #8 for mididings](https://github.com/dsacre/mididings/issues/8).

**Comment by dsacre** [comment]
the latest pysmf 0.1.1 release is now listed, with a source package hosted on PyPI.
